import os 
import shutil
import filecmp

# the purpose of this file is to swap the automatically generated _index.sldl file with the one generated by sldl-helper.py
# it also keeps a copy of each index file before making changes
def main():
	CURRENT_DIR = os.getcwd()
	SLDL_HELPER_DIR = CURRENT_DIR + "\\sldl-helper"
	SLDL_HELPER_INDEX_PATH = SLDL_HELPER_DIR + "\\sldl-helper_index.sldl"
	SLDL_INDEX_HISTORY_DIR = SLDL_HELPER_DIR + "\\_index-history"
	subfolder_names = [item for item in os.listdir(CURRENT_DIR) if os.path.isdir(os.path.join(CURRENT_DIR, item))]

	# if the script was not run in the directory sldl was ran, raise an exception
	if len(subfolder_names) == 1 and subfolder_names[0] == "sldl-helper":
		SLDL_INDEX_DIR = input("Could not find sldl index directory, creating it with custom index file, please enter spotify playlist name: ")
		os.mkdir(SLDL_INDEX_DIR)
		shutil.copy(SLDL_HELPER_INDEX_PATH, SLDL_INDEX_DIR + "\\_index.sldl")

		# raise Exception("Cannot find sldl-helper directory, please run sldl first, then run this script from in the same directory.")


	# if the number of subfolders in the directory is 2, one is the sldl-helper directory, and the other is the directory created by sldl containing _index.sldl
	subfolder_names = [item for item in os.listdir(CURRENT_DIR) if os.path.isdir(os.path.join(CURRENT_DIR, item))]	
	if len(subfolder_names) == 2:
		subfolder_names.remove('sldl-helper')
		SLDL_INDEX_PATH = f"{CURRENT_DIR}\\{subfolder_names[0]}\\_index.sldl"
	# if there are more than two subdirectories, we don't know which one contains _index.sldl so we need its path from the user
	else:
		SLDL_INDEX_PATH = input("Could not find automatically find _index.sldl, please enter its path: ")

	# if the sldl history dir doesn't already exist, create it
	if not os.path.exists(SLDL_INDEX_HISTORY_DIR):
		os.mkdir(SLDL_INDEX_HISTORY_DIR)

	# TODO: prevent recopying identical files to the history directory if there were no changes
	NUM_INDEX_HISTORY_FILES = len(os.listdir(SLDL_INDEX_HISTORY_DIR))

	# move the old auto generated index file to the history folder, and copy ours into its place
	shutil.move(SLDL_INDEX_PATH, f"{SLDL_INDEX_HISTORY_DIR}\\_index({NUM_INDEX_HISTORY_FILES}).sldl")
	shutil.copy(SLDL_HELPER_INDEX_PATH, SLDL_INDEX_PATH)
	print("\nSuccessfully swapped auto generated _index.sldl, with custom _index.sldl.\n")

if __name__ == "__main__":
	main()