import os 
import shutil
import sys

# returns true if two index files have identical contents
def check_index_file_equality(filepath_a: str, filepath_b: str) -> bool: 
	are_files_equal: bool = True

	with open(filepath_a, "r", encoding="utf-8") as file_a:
		with open(filepath_b, "r", encoding="utf-8") as file_b:
			for line_a, line_b in zip(file_a, file_b):
				# sldl swaps the state to 3 (file already exists) if ran in the same directory more than once. my script always uses 1 (successfully downloaded), so replace ,3, with ,1, just for the purposes of checking equality
				cleaned_line_a = line_a.replace(",3,", ",1,")
				cleaned_line_b = line_b.replace(",3,", ",1,")
				
				if cleaned_line_a != cleaned_line_b:
					are_files_equal = False
					break

	return are_files_equal

# the purpose of this script is to swap the automatically generated _index.sldl file with the one generated by sldl-helper.py
def main():
	CURRENT_DIR = sys.argv[1]
	SLDL_HELPER_DIR = CURRENT_DIR + "\\sldl_helper"
	SLDL_HELPER_INDEX_PATH = SLDL_HELPER_DIR + "\\_index.sldl"
	SLDL_INDEX_HISTORY_DIR = SLDL_HELPER_DIR + "\\_index_history"
	subfolder_names = [item for item in os.listdir(CURRENT_DIR) if os.path.isdir(os.path.join(CURRENT_DIR, item))]

	# if the number of subfolders in the directory is 2, one is the sldl-helper directory, and the other is the directory created by sldl containing _index.sldl
	subfolder_names = [item for item in os.listdir(CURRENT_DIR) if os.path.isdir(os.path.join(CURRENT_DIR, item))]	
	if len(subfolder_names) == 2:
		subfolder_names.remove('sldl_helper')
		SLDL_INDEX_PATH = f"{CURRENT_DIR}\\{subfolder_names[0]}\\_index.sldl"
	# if there are more than two subdirectories, we don't know which one contains _index.sldl so we need its path from the user
	else:
		SLDL_INDEX_PATH = input("Could not find automatically find _index.sldl, please enter its path: ")

	# if the sldl history dir doesn't already exist, create it
	if not os.path.exists(SLDL_INDEX_HISTORY_DIR):
		os.mkdir(SLDL_INDEX_HISTORY_DIR)

	# don't touch the index files if an identical one already exists in the history directory 
	index_history_files = [os.path.join(SLDL_INDEX_HISTORY_DIR, filename) for filename in os.listdir(SLDL_INDEX_HISTORY_DIR) if os.path.isfile(os.path.join(SLDL_INDEX_HISTORY_DIR, filename))]
	for history_file in index_history_files:
		if check_index_file_equality(history_file, SLDL_INDEX_PATH) == True:
			print("\n_index.sldl already up to date, nothing to do. Exiting...\n")
			return

	NUM_INDEX_HISTORY_FILES = len(os.listdir(SLDL_INDEX_HISTORY_DIR))

	# move the old auto generated index file to the history folder, and copy ours into its place
	shutil.move(SLDL_INDEX_PATH, f"{SLDL_INDEX_HISTORY_DIR}\\_index({NUM_INDEX_HISTORY_FILES}).sldl")
	shutil.copy(SLDL_HELPER_INDEX_PATH, SLDL_INDEX_PATH)
	print("\nSuccessfully swapped auto generated _index.sldl, with custom _index.sldl.\n")

if __name__ == "__main__":
	main()